name: CI/CD Pipeline for Hospital Appointment App

on:
  push:
    branches: [ host ]
  pull_request:
    branches: [ host ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run lint || true

      - name: Run real frontend tests (Vitest)
        run: npm run vitestd

      - name: ⚙️ Build Vite frontend
        run: npm run build

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/host'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Vite frontend
        run: npm run build

      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "yashavanthap.btech23@gmail.com"
          git config --global user.name "yashavanthap55"
          npm run deploy
